### ISSUE TITLE
click once update failed

### ISSUE THREAD

**Issue by psllc** [NuGetPackageExplorer/NuGetPackageExplorer#100]
PLATFORM VERSION INFO
	Windows 			: 10.0.10586.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1078.0 built by: NETFXREL3STAGE
	clr.dll 			: 4.6.1078.0 built by: NETFXREL3STAGE
	dfdll.dll 			: 4.6.1038.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.10586.0 (th2_release.151029-1700)

SOURCES
	Deployment url			: file:///C:/Users/mlloyd/AppData/Roaming/Microsoft/Windows/Start%20Menu/Programs/NuGet%20Package%20Explorer/NuGet%20Package%20Explorer.appref-ms%7C
						Server		: Microsoft-IIS/8.0,CDS01
						X-Powered-By	: ASP.NET
						X-AspNet-Version: 4.0.30319
	Deployment Provider url		: https://npe.codeplex.com/releases/clickonce/NuGetPackageExplorer.application
	Application url			: https://npe.codeplex.com/releases/clickonce/Application%20Files/NuGetPackageExplorer_3_15_0_0/NuGetPackageExplorer.exe.manifest
						Server		: Microsoft-IIS/8.0,CDS01
						X-Powered-By	: ASP.NET
						X-AspNet-Version: 4.0.30319

IDENTITIES
	Application Identity		: NuGetPackageExplorer.exe, Version=3.15.0.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86, type=win32

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\mlloyd\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\NuGet Package Explorer\NuGet Package Explorer.appref-ms| resulted in exception. Following failure messages were detected:
		+ Downloading https://npe.codeplex.com/releases/clickonce/Application Files/NuGetPackageExplorer_3_15_0_0/Humanizer.dll.deploy did not succeed.
		+ The remote server returned an error: (500) Internal Server Error.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [5/2/2016 9:39:15 AM] : Activation of C:\Users\mlloyd\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\NuGet Package Explorer\NuGet Package Explorer.appref-ms| has started.
	* [5/2/2016 9:39:15 AM] : Performing necessary update check as specified by the deployment.
	* [5/2/2016 9:39:15 AM] : Consuming new update.
	* [5/2/2016 9:39:29 AM] : Installation of the application has started.
	* [5/2/2016 9:39:30 AM] : Processing of application manifest has successfully completed.
	* [5/2/2016 9:39:30 AM] : Found compatible runtime version 4.0.30319.
	* [5/2/2016 9:39:30 AM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [5/2/2016 9:40:01 AM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading https://npe.codeplex.com/releases/clickonce/Application Files/NuGetPackageExplorer_3_15_0_0/Humanizer.dll.deploy did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.ConsumeUpdatedDeployment(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentUpdate(SubscriptionState& subState, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ProcessOrFollowShortcut(String shortcutFile, String& errorPageUrl, TempFile& deployFile)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The remote server returned an error: (500) Internal Server Error.
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by psllc** [comment]
Note that each time i tried this it got a little further.  after about ten tries i had the update.   my current service provider is Comcast with speeds measured at 78mbits/sec down and 12mbits/sec up.

**Comment by 304NotModified** [comment]
You can try 3.16, but dunno why codeplex would return ` (500) Internal Server Error.` (as seen in your logs)

There is also a chocolatey package. Maybe that one has more luck.

**Comment by 304NotModified** [comment]
AFAIK we can't fix this. As alternative you can use the [chocolatey package](https://chocolatey.org/packages/NugetPackageExplorer).

**Comment by psllc** [comment]
thank you.
