### ISSUE TITLE
Signing fails with Timestamp Server Error

### ISSUE THREAD

**Issue by RickStrahl** [NuGetPackageExplorer/NuGetPackageExplorer#1050]
- Bug

With the latest version of the Package Explorer I'm getting errors for the timestamp server of `The reply from the Timestamp server was invalid` for the same timestamp URL I've been using for a long time:

![image](https://user-images.githubusercontent.com/1374013/85933634-f1c29600-b874-11ea-8784-0b13903db47b.png)

Also verified that the timestamp server seems to work if I manually sign some other binaries using SignTool, so the timestamp server appears to be working correctly.

NuGet Package Explorer - Chocolatey - X64 - (5.7.98+fbe38e7088), Windows 10, 2004

**Comment by RickStrahl** [comment]
Also verified that directly using the Nuget command line to sign works:

```ps
nuget sign  ".\nupkg\$filename"   -CertificateSubject "West Wind Technologies" -timestamper "http://timestamp.digicert.com"
```

**Comment by clairernovotny** [comment]
@bartonjs 

There's a difference between how .NET Core does it and .NET Framework here...

**Comment by bartonjs** [comment]
Presumably DigiCert has made an invalid timestamp object.  If you can capture it maybe we can figure out how to report their illegal encoding to them.

If this is the same problem that we've seen before: .NET Framework / Win32 is a bit lax in their decoding, and they don't complain about BER/DER Integer values that have an invalid encoding (perhaps they complain when they go to interpret it as a number); but since my decoder knows it's an Integer value it checks that it makes sense, and is then rejecting it for having an extra padding byte.

**Comment by RickStrahl** [comment]
Maybe the easier solution is to use different timestamp server. Using that one because... well, I've been using it for a long time. Any suggestions for a different timestamp service to use?

**Comment by RickStrahl** [comment]
Tried with another timestamp server (the one that is officially recommended for my cert) and I get the same issue:

![image](https://user-images.githubusercontent.com/1374013/85935301-db273980-b88a-11ea-9555-7c64edd75db7.png)

**Comment by clairernovotny** [comment]
Can you please post signed packages here using the NuGet exe and each of the TSA’s? Just rename to zip and attach to the comment.

**Comment by campersau** [comment]
I tracked the isssue down in NuGet.Client, see https://github.com/NuGet/Home/issues/9725

**Comment by heng-liu** [comment]
Here are few packages with the bad-formatted timestamp: 
CaesarCRM.Api   18.3.7352.13985
Westwind.Web    2.81.0
Magick.NET.Web-Q8-x64   7.16.1
The serialNumber of timestamp in those packages doesn't satisfy the "minimum number of bytes" rule.

**Comment by ITAgnesmeyer** [comment]
### The client do not accept any timestamp server.

So what is the solution?

There is no way to upload a Nuget-Package to Nutet any more.

nuget.exe also do not work anymore!

If it is a problem of .NET core 5.0 how is the solution?


   at NuGet.Packaging.Signing.Rfc3161TimestampRequestNetstandard21Wrapper.<SubmitRequestAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Packaging.Signing.Rfc3161TimestampProvider.<GetTimestampAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Packaging.Signing.Rfc3161TimestampProvider.<TimestampSignatureAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Packaging.Signing.SigningUtility.<SignAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PackageExplorerViewModel.SignPackageViewModel.<SignPackage>d__67.MoveNext() in O:\dev\NuGetPackageExplorer-main\PackageViewModel\SignPackageViewModel.cs:line 322

**Comment by clairernovotny** [comment]
@ITAgnesmeyer this was a bug and just fixed. The latest nightly has the fix.

**Comment by ITAgnesmeyer** [comment]
@clairernovotny Thank you verry much. Now it works.

**Comment by RickStrahl** [comment]
Thank you! Checked with latest release (5.7.103) and it now works again.
