### ISSUE TITLE
Install fails possible/probably due to authenticated proxy

### ISSUE THREAD

**Issue by softwarecraft** [NuGetPackageExplorer/NuGetPackageExplorer#108]
Hi!

**Type**: Bug / Feature Request
**NPE version**: 3.16
**Installed from**: ClickOnce

In case of a BUG:
- What is the current result? Error msg
- What is the expected result? Success
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions) See attachment
- Are there any work arounds? No
- Is there a version in which it did worked? No
- Is there a package on Nuget.org which shows the bug? No

In case of FEATURE REQUEST:
 - Why do we need it? In a corporate environment with an authenticated proxy firewall it is not possible to install NPE. Please provide either the ability to specify credentials for an authenticated proxy or an alternate installer not Click Once.
 - Please provide an use case. Same

![nuget package explorer - click once download - cannot start application - application download did not succeed](https://cloud.githubusercontent.com/assets/12091402/15873358/5a61fbe4-2ccc-11e6-96cb-a34389241d8e.PNG)

[NuGet Package Manager - Click Once download - 41IK12NC.log.txt](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/files/303468/NuGet.Package.Manager.-.Click.Once.download.-.41IK12NC.log.txt)

**Comment by 304NotModified** [comment]
```
	* [07/06/2016 4:12:38 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading https://npe.codeplex.com/releases/clickonce/NuGetPackageExplorer.application did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirect(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.FollowDeploymentProviderUri(SubscriptionStore subStore, AssemblyManifest& deployment, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- Unable to connect to the remote server
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Net.Sockets.SocketException
		- A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 65.52.103.72:443
		- Source: System
		- Stack trace:
			at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
			at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
```

I don't think we fix this. This is your internet connection or codeplex. :(

**Comment by 304NotModified** [comment]
You can use the [chocolatey](https://chocolatey.org/packages/NugetPackageExplorer_ package?
