### ISSUE TITLE
Exception during save and publish

### ISSUE THREAD

**Issue by gdosborne** [NuGetPackageExplorer/NuGetPackageExplorer#117]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

X Bug

version 3.18.0

**Installed from**: ClickOnce

In case of a BUG:
- What is the current result?
  "Block length does not match with it's complement" on second save of session then "Object reference not set to instance of an object" during file save thereafter
- What is the expected result?
  Saved file
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)

```
   at System.IO.Compression.Inflater.DecodeUncompressedBlock(Boolean& end_of_block)
  at System.IO.Compression.Inflater.Decode()
  at System.IO.Compression.Inflater.Inflate(Byte[] bytes, Int32 offset, Int32 length)
  at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
  at MS.Internal.IO.Packaging.DeflateEmulationTransform.Decompress(Stream source, Stream sink)
  at MS.Internal.IO.Packaging.CompressEmulationStream..ctor(Stream baseStream, Stream tempStream, Int64 position, IDeflateTransform transformer)
  at MS.Internal.IO.Packaging.CompressStream.ChangeMode(Mode newMode)
  at MS.Internal.IO.Packaging.CompressStream.Seek(Int64 offset, SeekOrigin origin)
  at MS.Internal.IO.Zip.ProgressiveCrcCalculatingStream.Seek(Int64 offset, SeekOrigin origin)
  at MS.Internal.IO.Zip.ZipIOModeEnforcingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
  at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
  at System.IO.Stream.CopyTo(Stream destination)
  at NuGet.PackageBuilder.CreatePart(Package package, String path, Stream sourceStream) in c:\Users\Greg\Desktop\NuGetPackageExplorer-master\Core\Authoring\PackageBuilder.cs:line 418
  at NuGet.PackageBuilder.WriteFiles(Package package) in c:\Users\Greg\Desktop\NuGetPackageExplorer-master\Core\Authoring\PackageBuilder.cs:line 354
  at NuGet.PackageBuilder.Save(Stream stream) in c:\Users\Greg\Desktop\NuGetPackageExplorer-master\Core\Authoring\PackageBuilder.cs:line 159
  at PackageExplorerViewModel.PackageHelper.SavePackage(IPackageMetadata packageMetadata, IEnumerable`1 files, String targetFilePath, Boolean useTempFile) in c:\Users\Greg\Desktop\NuGetPackageExplorer-master\PackageViewModel\Utilities\PackageHelper.cs:line 33
  at PackageExplorerViewModel.PackageViewModel.GetCurrentPackageTempFile() in c:\Users\Greg\Desktop\NuGetPackageExplorer-master\PackageViewModel\PackageViewModel.cs:line 1111
  at PackageExplorerViewModel.PublishPackageViewModel..ctor(MruPackageSourceManager mruSourceManager, ISettingsManager settingsManager, PackageViewModel viewModel) in c:\Users\Greg\Desktop\NuGetPackageExplorer-master\PackageViewModel\PublishPackage\PublishPackageViewModel.cs:line 39
  at PackageExplorerViewModel.PackageViewModel.PublishExecute() in c:\Users\Greg\Desktop\NuGetPackageExplorer-master\PackageViewModel\PackageViewModel.cs:line 724
  at PackageExplorerViewModel.RelayCommand.Execute(Object parameter) in c:\Users\Greg\Desktop\NuGetPackageExplorer-master\PackageViewModel\Commands\RelayCommand.cs:line 155
  at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
  at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
  at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
  at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
  at System.Windows.Threading.DispatcherOperation.InvokeImpl()
  at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
  at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
  at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
  at System.Windows.Threading.DispatcherOperation.Invoke()
  at System.Windows.Threading.Dispatcher.ProcessQueue()
  at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
  at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
  at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
  at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
  at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
  at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
  at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
  at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
  at System.Windows.Application.RunDispatcher(Object ignore)
  at System.Windows.Application.RunInternal(Window window)
  at System.Windows.Application.Run(Window window)
  at System.Windows.Application.Run()
  at PackageExplorer.App.Main() in c:\Users\Greg\Desktop\NuGetPackageExplorer-master\PackageExplorer\obj\x86\Debug\App.g.cs:line 0
  at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
  at System.AppDomain.nExecuteAssembly(RuntimeAssembly assembly, String[] args)
  at System.Runtime.Hosting.ManifestRunner.Run(Boolean checkAptModel)
  at System.Runtime.Hosting.ManifestRunner.ExecuteAsAssembly()
  at System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext activationContext, String[] activationCustomData)
  at System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext activationContext)
  at System.Activator.CreateInstance(ActivationContext activationContext)
  at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssemblyDebugInZone()
  at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
  at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
  at System.Threading.ThreadHelper.ThreadStart()

```
- Are there any work arrounds? yes
  Shut down application and save again. Always happens on second save of package. First save after package is opened succeeds. Any subsequent saves throw exception.
- Is there a version in which it did worked? 
  Unknown
- Is there a package on Nuget.org which shows the bug?
  Unknown

Package I am creating has only a single assembly with not dependencies or

**Comment by 304NotModified** [comment]
If you help us finding the source of this bug, that would be appreciated!

**Comment by gdosborne** [comment]
No problem. Once I get an opportunity I'll take a look at it.

**Comment by timandy** [comment]
when I save a apackage the app not work.

**Comment by 304NotModified** [comment]
Closing this due to inactivity. Please let us know if this still an issue and please provide the requested info.

**Comment by 304NotModified** [comment]
@timandy feel free to open a new issue
