### ISSUE TITLE
Entry point was not found when searching in some online feeds

### ISSUE THREAD

**Issue by bveldkamp** [NuGetPackageExplorer/NuGetPackageExplorer#1284]
When trying to open a package from an online feed, no packages are found, but a message at the bottom of the _Select Package_ window says: _Entry point was not found_. Steps to reproduce:

- Start Package Explorer
- Click on _Open a package from online feed_
- Select Package Source: _https://api.nuget.org/v3/index.json_
- Th error should immediately be visible, otherwise search for an arbitrary text

Using Fiddler, I can see that requests to that feed are made, and that some JSON is returned with the names of the packages I was searching for. Package sources that do not work include https://api.nuget.org/v3/index.json and https://pkgs.dev.azure.com/MYTEAM/_packaging/MYTEAM/nuget/v3/index.json
We have an older local repository that communicates with XML, this one still works. 
Also, uploading a _new_ package to our Azure feed does work too.

**Type** (choose one):

- Bug

**NPE version**: 5.10.21

**OS version**: Windows 10 - 1909

**Installed from**: Chocolatey.org 

In case of a BUG:

- What is the current result? No packages are listed in the _Select Package_ window
- What is the expected result? Packages should be listed
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions). No exception observed
- Are there any workarounds? no
- Is there a version in which it did work? I don't know
- Is there a package on Nuget.org which shows the bug? N/A

**Comment by mmb5** [comment]
I also started receiving the same error of _Entry point was not found_.  I was also having the issue in Visual Studio, and I was able to repair the issue with the steps outlined here: https://cann0nf0dder.wordpress.com/2019/07/20/visual-studio-nuget-no-connection-could-be-made-because-the-target-machine-actively-refused-it-127-0-0-18888/.  However, I don't see a similar config file in NPE to change.

**Comment by campersau** [comment]
I see the same error when using the windows store version (`NuGet Package Explorer - Store - X64 - (5.10.21+6a2d01cb3f)`). But when I debug the code it works.
@clairernovotny do you see some more information in application insights?

**Comment by clairernovotny** [comment]
I'm not seeing anything in app insights

**Comment by clairernovotny** [comment]
I'm guessing there's a bug in .NET 6 preview 4. I'm reverting to preview 3 and it's building now.

**Comment by campersau** [comment]
Yes, it works again with the new version https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/releases/tag/v5.10.25

**Comment by campersau** [comment]
I have reported the issue to dotnet here: https://github.com/dotnet/runtime/issues/53520

Depending on if this gets fixed we could update to a newer version of `Newtonsoft.Json`. Currently we are using the old `9.0.1` version from `NuGet.Packaging`.

Just for reference here is the complete stack trace:

```
System.EntryPointNotFoundException: Entry point was not found.
   at System.Collections.Generic.IEnumerable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) in System.Private.CoreLib.dll:token 0x60065c5+0x5c
   at Newtonsoft.Json.Utilities.ReflectionUtils.GetFields(Type targetType, BindingFlags bindingAttr) in Newtonsoft.Json.dll:token 0x6000431+0x0
   at Newtonsoft.Json.Utilities.ReflectionUtils.GetFieldsAndProperties(Type type, BindingFlags bindingAttr) in Newtonsoft.Json.dll:token 0x6000428+0x0
   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetSerializableMembers(Type objectType) in Newtonsoft.Json.dll:token 0x60004b0+0xa
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization) in Newtonsoft.Json.dll:token 0x60004cc+0x0
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType) in Newtonsoft.Json.dll:token 0x60004b2+0xe
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType) in Newtonsoft.Json.dll:token 0x60004c7+0xc9
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type) in Newtonsoft.Json.dll:token 0x60004af+0x38
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in Newtonsoft.Json.dll:token 0x60005df+0xe
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in Newtonsoft.Json.dll:token 0x6000152+0x45
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer) in Newtonsoft.Json.dll:token 0x600093e+0x11
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer) in Newtonsoft.Json.dll:token 0x600093d+0x0
   at NuGet.Protocol.JsonExtensions.FromJToken[T](JToken jtoken) in NuGet.Protocol.dll:token 0x6000076+0x0
   at PackageExplorerViewModel.ShowLatestVersionQueryContext`1.<>c.<SearchOnServer>b__17_2(JObject s) in C:\dev_projects\NuGetPackageExplorer\PackageViewModel\PackageChooser\ShowLatestVersionQueryContext.cs:line 119
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList() in System.Linq.dll:token 0x60001bc+0x1b
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) in System.Linq.dll:token 0x600011b+0x1b
   at PackageExplorerViewModel.ShowLatestVersionQueryContext`1.<>c__DisplayClass17_0.<<SearchOnServer>b__1>d.MoveNext() in C:\dev_projects\NuGetPackageExplorer\PackageViewModel\PackageChooser\ShowLatestVersionQueryContext.cs:line 119
--- End of stack trace from previous location ---
   at PackageExplorerViewModel.ShowLatestVersionQueryContext`1.SearchOnServer(CancellationToken token) in C:\dev_projects\NuGetPackageExplorer\PackageViewModel\PackageChooser\ShowLatestVersionQueryContext.cs:line 114
   at PackageExplorerViewModel.ShowLatestVersionQueryContext`1.LoadMore(CancellationToken token) in C:\dev_projects\NuGetPackageExplorer\PackageViewModel\PackageChooser\ShowLatestVersionQueryContext.cs:line 54
   at PackageExplorerViewModel.PackageChooserViewModel.LoadMore(CancellationToken token) in C:\dev_projects\NuGetPackageExplorer\PackageViewModel\PackageChooser\PackageChooserViewModel.cs:line 283
```

**Comment by bveldkamp** [comment]
Thanks for the quick fix. I got 5.10.25 from the Windows Store today

**Comment by campersau** [comment]
@clairernovotny another workaround is to set `<PublishReadyToRunUseCrossgen2>false</PublishReadyToRunUseCrossgen2>` in the publish profiles if you want to run on the latest .net previews again.

- https://github.com/dotnet/core/issues/6098#issuecomment-827045193
- https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-4/#publishreadytorun-now-uses-crossgen2-by-default

**Comment by clairernovotny** [comment]
@campersau were you able to test/reproduce this?

**Comment by clairernovotny** [comment]
NM, confirmed it locally.
