### ISSUE TITLE
with net6 rc1 installed, no any response when running the published NuGetPackageExplorer.exe for 6.0 NPE solution.

### ISSUE THREAD

**Issue by vdanche** [NuGetPackageExplorer/NuGetPackageExplorer#1350]
Affected Branch: main
Affected Build: Version 17.0.0 Preview 4.0 [31618.318.main]+ NET 6 SDK: 6.0.100-rc.1.21418.40
Affected Product Language:

**Steps to reproduce:**
NugetPackageExplorer [Windows] [Framework Dependent]

                  

1. Clone NuGetPackageExplorer Repo   Fot .net 6: git clone https://github.com/NuGetPackageExplorer/NuGetPackageExplorer 
2. Build the solution in CLI. We are using below steps to build the solution although they will publish also.

            Go to the \NuGetPackageExplorer\PackageExplorer directory

 

dotnet publish -c Release -r win-x64 /p:PublishReadyToRun=true /p:SelfContained=true NuGetPackageExplorer.csproj
Launch bin\Release\net6.0-windows10.0.19041\win-x64\publish\NuGetPackageExplorer.exe, go to “Open a package from online feed.” There shouldn’t be any errors.
 

**Expected Result:**

Run NuGetPackageExplorer.exe succeed without any issue.

**Actual Result:**

no any response when running the published NuGetPackageExplorer.exe for 6.0 NPE solution.

![image](https://user-images.githubusercontent.com/65637796/130413667-ca660415-1f9b-4e77-a934-51ac7f6f675a.png)

**Note:**

In VS, the same issue happen when publish succeed.

Open NuGetPackageExplorer.sln in VS 2022
Open Configuration manager and set: 

Configuration to Release
Set Platform to x86 (add the configuration).

.Publish the  NuGetPackageExplorer.csproj project as a framework-dependent app
Create a new FolderProfile 
Edit the settings to the following (if not chosen by default)
Configuration = Release|X86
Target Framework = net6.0
Deploy mode = Framework Dependent
Target Runtime = Portable
Publish
Run the published NuGetPackageExplorer.exe(Do this under the specific published folder) and try out a few options.

dotnet --info

.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21418.40
 Commit:    4bef385e31

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22443
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21418.40\

Host (useful for support):
  Version: 6.0.0-rc.1.21418.9
  Commit:  2a28e2f015

.NET SDKs installed:
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21418.40 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21418.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21418.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21418.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by clairernovotny** [comment]
Is there issue filed elsewhere on the runtime repo? The root cause is not going to be with NPE.

**Comment by campersau** [comment]
I can confirm that this also does not work with `6.0.0-rc.2.21420.29`. 

Here is the output from windows event viewer.

```
Application: NuGetPackageExplorer.exe
CoreCLR Version: 6.0.21.42029
.NET Version: 6.0.0-rc.2.21420.29
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: Beim Festlegen der Eigenschaft "System.Windows.ResourceDictionary.DeferrableContent" wurde eine Ausnahme ausgelöst.
 ---> System.PlatformNotSupportedException: System.Windows.Extensions types are not supported on this platform.
   at System.Xaml.Permissions.XamlAccessLevel.AssemblyAccessTo(Assembly assembly)
   at System.Windows.SystemResources.ResourceDictionaries.LoadDictionary(Assembly assembly, String assemblyName, String resourceName, Boolean isTraceEnabled, Uri& dictionarySourceUri)
   at System.Windows.SystemResources.ResourceDictionaries.LoadThemedDictionary(Boolean isTraceEnabled)
   at System.Windows.SystemResources.FindDictionaryResource(Object key, Type typeKey, ResourceKey resourceKey, Boolean isTraceEnabled, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean& canCache)
   at System.Windows.SystemResources.FindResourceInternal(Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.FrameworkElement.FindResourceInternal(FrameworkElement fe, FrameworkContentElement fce, DependencyProperty dp, Object resourceKey, Object unlinkedParent, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, DependencyObject boundaryElement, Boolean isImplicitStyleLookup, Object& source)
   at System.Windows.StaticResourceExtension.FindResourceInAppOrSystem(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.StaticResourceExtension.FindResourceInEnviroment(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.StaticResourceExtension.TryProvideValueImpl(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.ResourceDictionary.SetOptimizedStaticResources(IList`1 staticResources, IServiceProvider serviceProvider, StaticResourceExtension staticResourceWorker)
   at System.Windows.ResourceDictionary.SetKeys(IList`1 keyCollection, IServiceProvider serviceProvider)
   at System.Windows.ResourceDictionary.SetDeferrableContent(DeferrableContent deferrableContent)
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__297_0(Object target, Object value)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at PackageExplorer.App.InitializeComponent() in P:\NuGetPackageExplorer\PackageExplorer\App.xaml:line 1
   at PackageExplorer.App.Main()
```

And even when debugging in `Debug` mode:

```
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Nachricht = Zeilennummer "14" und Zeilenposition "37" von "Beim Festlegen der Eigenschaft "System.Windows.ResourceDictionary.DeferrableContent" wurde eine Ausnahme ausgelöst.".
  Quelle = PresentationFramework
  Stapelüberwachung:
   bei System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   bei System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   bei System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   bei System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   bei PackageExplorer.App.InitializeComponent() in C:\dev_projects\NuGetPackageExplorer\PackageExplorer\App.xaml: Zeile1

  Diese Ausnahme wurde ursprünglich von dieser Aufrufliste ausgelöst:
    [Externer Code]

Innere Ausnahme 1:
PlatformNotSupportedException: System.Windows.Extensions types are not supported on this platform.
```

![image](https://user-images.githubusercontent.com/4009570/130447810-cb983603-f7c4-4215-8e2c-64a308439651.png)

So I am not sure if it is a runtime or wpf bug.

@vdanche can you see something in the windows event viewer as well?

**Comment by campersau** [comment]
I get the same exception when creating a completly new and empty WPF app.

**Comment by ryalanms** [comment]
The incorrect runtime dependency version issue is tracked here:  https://github.com/dotnet/sdk/issues/19871.

**Comment by vdanche** [comment]
Not repro on 6.0.100-rc.1.21424.1(runtime-6.0.0-rc.1.21423.9)
