### ISSUE TITLE
Error while deploying a release

### ISSUE THREAD

**Issue by rahullunia** [NuGetPackageExplorer/NuGetPackageExplorer#1353]
Hi, I am getting an error when running the pipeline to deploy it in Octopus Deploy

System.IO.DirectoryNotFoundException: Could not find a part of the path ‘D:\a\9\a\build_publishedWebsites\ISG.CDP.API’.
at System.IO.Enumeration.FileSystemEnumerator1.CreateDirectoryHandle(String path, Boolean ignoreNotFound) at System.IO.Enumeration.FileSystemEnumerator1…ctor(String directory, EnumerationOptions options)
at System.IO.Enumeration.FileSystemEnumerable1..ctor(String directory, FindTransform transform, EnumerationOptions options) at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options) at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options) at NuGet.Common.PathResolver.PerformWildcardSearch(String basePath, String searchPath, Boolean includeEmptyDirectories, String& normalizedBasePath) at NuGet.Packaging.PackageBuilder.ResolveSearchPattern(String basePath, String searchPath, String targetPath, Boolean includeEmptyDirectories) at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable1 files)
at Octopus.Cli.Commands.Package.NuGetPackageBuilder.BuildPackage(String basePath, IList`1 includes, ManifestMetadata metadata, String outFolder, Boolean overwrite, Boolean verboseInfo) in C:\BuildAgent\work\289bf0fca31007af\source\Octopus.Cli\Commands\Package\NuGetPackageBuilder.cs:line 39
at Octopus.Cli.Commands.Package.PackCommand.<>c_DisplayClass21_0.<Execute>b_0() in C:\BuildAgent\work\289bf0fca31007af\source\Octopus.Cli\Commands\Package\PackCommand.cs:line 167
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
— End of stack trace from previous location where exception was thrown —
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
— End of stack trace from previous location where exception was thrown —
at Octopus.Cli.CliProgram.Run(String[] args) in C:\BuildAgent\work\289bf0fca31007af\source\Octopus.Cli\CliProgram.cs:line 54
Exit code: -3

Could you please help?

The failure is in the Package step
![image](https://user-images.githubusercontent.com/66118230/131090320-b487dc65-b96d-458b-a74e-e10175645bdc.png)

I tried to give the path directly browsing the Project folder, but it only deploys an incomplete package, not the expected full package

**Comment by alexandermlharris** [comment]
I'm guessing this is the wrong repository for this request? Looks like a question RE nuget itself, not the package expolorer?
