### ISSUE TITLE
Failed installing NuGetPackageExplorer

### ISSUE THREAD

**Issue by aaronmi** [NuGetPackageExplorer/NuGetPackageExplorer#165]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):
- Bug

**NPE version**: (e.g. 3.12) (see Help -> about)
3.21

**Installed from**: ClickOnce / chocolatey.org / Zip on CodePlex 
GitHub

In case of a BUG:

[GOVE1PDA.txt](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/files/696736/GOVE1PDA.txt)

in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - Please provide an use case.

**Comment by 304NotModified** [comment]
this is clickonce?

**Comment by 304NotModified** [comment]
- Downloading https://npe.codeplex.com/releases/clickonce/Application Files/NuGetPackageExplorer_3_21_0_0/CodeExecutor.dll.deploy did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The remote server returned an error: (500) Internal Server Error.

---

We cannot fix that

**Comment by onovotny** [comment]
ClickOnce is unstable. Recommendation is to use the Windows Store app (same as the desktop) if you have Windows 10 Anniversary Update or later: https://www.microsoft.com/store/apps/9wzdncrdmdm3
