### ISSUE TITLE
Unable to download/install

### ISSUE THREAD

**Issue by yurilausberg** [NuGetPackageExplorer/NuGetPackageExplorer#174]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug
- Feature request
- Question

**NPE version**: (e.g. 3.12) (see Help -> about)

**Installed from**: ClickOnce / chocolatey.org / Zip on CodePlex 

In case of a BUG:

- What is the current result?
- What is the expected result?
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
- Are there any work arrounds? yes/no
- Is there a version in which it did worked? 
- Is there a package on Nuget.org which shows the bug?

in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - Please provide an use case.

**Comment by 304NotModified** [comment]
Please fill in the template

**Comment by yurilausberg** [comment]
Sorry, here was the error I got repeatedly, until it worked again...
ERROR DETAILS
	Following errors were detected during this operation.
	* [3/2/2017 9:15:51 AM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading https://npe.codeplex.com/releases/clickonce/Application Files/NuGetPackageExplorer_3_21_0_0/NuGetPackageExplorer.exe.manifest did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The remote server returned an error: (500) Internal Server Error.
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

**Comment by 304NotModified** [comment]
Unfortunately codeplex.com gives a http 500 and we cannot fix this. :(

Its a common error. Would recommend chocolatey.

**Comment by 304NotModified** [comment]
:( 

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues?utf8=%E2%9C%93&q=label%3A%22install%20error%22%20label%3Aclickonce

**Comment by tiesont** [comment]
@304NotModified So, is this basically a case where ClickOnce should be abandoned as an installation option? I haven't successfully been able to install it the last few times I tried (the link in the installer error dialog is an issue in and of itself). Would just a plain old installer be an option?

I've basically resorted to cloning and building a local copy at this point, since I find NPE too useful to just stop using... :(

**Comment by 304NotModified** [comment]
We are working on a Windows Store package and then we drop ClickOnce. 

I (and my colleges) never had problems with installing the ClickOnce. I really don't know what's triggering the 500

**Comment by onovotny** [comment]
ClickOnce is unstable. Recommendation is to use the Windows Store app (same as the desktop) if you have Windows 10 Anniversary Update or later: https://www.microsoft.com/store/apps/9wzdncrdmdm3
