### ISSUE TITLE
Unable to retrieve application files. Files corrupt in deployment

### ISSUE THREAD

**Issue by prassawant** [NuGetPackageExplorer/NuGetPackageExplorer#217]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NPE version**:3.21.0.0

**Installed from**: https://npe.codeplex.com/releases/clickonce/NuGetPackageExplorer.application

In case of a BUG:

- What is the current result?
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of D:\from Desktop\NuGet Package Explorer.appref-ms| resulted in exception. Following failure messages were detected:
		+ Exception occurred loading manifest from file Humanizer.dll: the manifest may not be valid or the file could not be opened. 
		+ File Humanizer.dll is not a valid Portable Executable (PE) file.
		+ File {0} is not a valid Portable Executable (PE) file.
- What is the expected result?
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2053.0 built by: NET47REL1
	clr.dll 			: 4.7.2053.0 built by: NET47REL1
	dfdll.dll 			: 4.7.2053.0 built by: NET47REL1
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: file:///D:/from%20Desktop/NuGet%20Package%20Explorer.appref-ms%7C
						Server		: Microsoft-IIS/7.5,CDS03
						X-Powered-By	: ASP.NET
						X-AspNet-Version: 4.0.30319
	Deployment Provider url		: https://npe.codeplex.com/releases/clickonce/NuGetPackageExplorer.application
	Application url			: https://npe.codeplex.com/releases/clickonce/Application%20Files/NuGetPackageExplorer_3_21_0_0/NuGetPackageExplorer.exe.manifest
						Server		: Microsoft-IIS/7.5,CDS03
						X-Powered-By	: ASP.NET
						X-AspNet-Version: 4.0.30319

IDENTITIES
	Application Identity		: NuGetPackageExplorer.exe, Version=3.21.0.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86, type=win32

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of D:\from Desktop\NuGet Package Explorer.appref-ms| resulted in exception. Following failure messages were detected:
		+ Exception occurred loading manifest from file Humanizer.dll: the manifest may not be valid or the file could not be opened. 
		+ File Humanizer.dll is not a valid Portable Executable (PE) file.
		+ File {0} is not a valid Portable Executable (PE) file.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [15/08/2017 13:40:21] : Activation of D:\from Desktop\NuGet Package Explorer.appref-ms| has started.
	* [15/08/2017 13:40:28] : Installation of the application has started.
	* [15/08/2017 13:40:29] : Processing of application manifest has successfully completed.
	* [15/08/2017 13:40:32] : Found compatible runtime version 4.0.30319.
	* [15/08/2017 13:40:32] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [15/08/2017 13:40:35] System.Deployment.Application.InvalidDeploymentException (ManifestLoad)
		- Exception occurred loading manifest from file Humanizer.dll: the manifest may not be valid or the file could not be opened. 
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.ManifestLoadExceptionHelper(Exception exception, String filePath)
			at System.Deployment.Application.Manifest.AssemblyManifest.LoadFromInternalManifestFile(String filePath)
			at System.Deployment.Application.DownloadManager.ProcessDownloadedFile(Object sender, DownloadEventArgs e)
			at System.Deployment.Application.FileDownloader.DownloadModifiedEventHandler.Invoke(Object sender, DownloadEventArgs e)
			at System.Deployment.Application.FileDownloader.OnModified()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.IO.IOException
		- File Humanizer.dll is not a valid Portable Executable (PE) file.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.PEStream.ConstructFromFile(String filePath, Boolean partialConstruct)
			at System.Deployment.Application.Manifest.AssemblyManifest.LoadFromInternalManifestFile(String filePath)
		--- Inner Exception ---
		System.ComponentModel.Win32Exception
		- File {0} is not a valid Portable Executable (PE) file.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.PEStream.DosHeader..ctor(FileStream file)
			at System.Deployment.Application.PEStream.ConstructPEImage(FileStream file, Boolean partialConstruct)
			at System.Deployment.Application.PEStream.ConstructFromFile(String filePath, Boolean partialConstruct)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by 304NotModified** [comment]
Clickonce/codeplex is buggy. Please retry or use the windows 10 store or chocolatey package.

**Comment by prassawant** [comment]
Hi
I am using windows 7 , could you please advise

**Comment by 304NotModified** [comment]
Use https://github.com/NuGetPackageExplorer/NuGetPackageExplorer#chocolatey

**Comment by dlemstra** [comment]
Please forgive me if I am hijacking this issue but my comment is related to the ClickOnce package on NuGet. I noticed that the ClickOnce package has not been updated in a while and CodePlex will shut down pretty soon so that means you could use a new spot for this. Do you have an azure account @304NotModified ? I had the same issue with a project of mine that also uses ClickOnce and was hosted on CodePlex. You can solve this by creating a free app in azure and launch the installer from there. If you don't have an azure account yourself I would be willing to let you host it in my azure account. And let me know if you need a bit more information.

**Comment by 304NotModified** [comment]
hi @dlemstra ,

I don't have a Azure account, but if it's free it could look at it.

The main question is, is it stable? As ClickOnce (only experience with hosted on CodePlex) is really giving issues. See https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues?q=label%3Aclickonce

**Comment by dlemstra** [comment]
It has been pretty stable so far. It's just a website that has the clickonce files hosted inside azure.

**Comment by 304NotModified** [comment]
@onovotny any opinion on also hosting ClickOnce on Azure, suggested by @dlemstra ?

**Comment by 304NotModified** [comment]
closing as clickonce is not supported anymore
