### ISSUE TITLE
FileNotFoundException, program crash at startup

### ISSUE THREAD

**Issue by InteXX** [NuGetPackageExplorer/NuGetPackageExplorer#312]
Hi! Thanks for reporting this feature/bug/question! 

Please keep/fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):
- Bug

**NPE version**: (e.g. 3.12) (see Help -> about)
File version: 3.24.21.23287 (from .EXE file properties dialog)

**Installed from**: ClickOnce / chocolatey.org / Zip on CodePlex / Windows Store
chocolatey.org (installed on Server 2016 Standard)

In case of a BUG:
- What is the current result? The program doesn't run, crashes at startup
- What is the expected result? The program should run
- Please post full exception details in case of an Exception (message, stack trace, inner exceptions) From application event log, see below
- Is there any workaround? No
- Is there a version in which it did work? No
- Is there a package on Nuget.org which shows the bug? N/A

--- Stack Trace ---------------------------------------------------------------------------------
Application: NuGetPackageExplorer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at PackageExplorer.App.get_Container()
   at PackageExplorer.App+<Application_Startup>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at PackageExplorer.App.Main()

**Comment by onovotny** [comment]
Can you please try the latest chocolatey release (4.0.0) and see if it repro's there?

**Comment by InteXX** [comment]
That works, thank you.
