### ISSUE TITLE
A local file header is corrupt

### ISSUE THREAD

**Issue by asiridissa** [NuGetPackageExplorer/NuGetPackageExplorer#376]
Bug
4.138
Windows Store

It displays following error message on save
--------------------------- NuGet Package Explorer ---------------------------
 A local file header is corrupt.
--------------------------- OK ---------------------------

Had no problems with the previous version.

I just copied the previous version of .nupkg file and rename it to the new version and after editing the file, on save the problem occurs.

**Comment by onovotny** [comment]
What package is this occurring with, can you attach it here (rename it to .zip)

**Comment by asiridissa** [comment]
Here is a package with the issue.

[Robot.Dimension.Tenant 1.0.4.1.zip](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/files/1833113/Robot.Dimension.Tenant.1.0.4.1.zip)

**Comment by onovotny** [comment]
I just opened it on my machine without issue:

![image](https://user-images.githubusercontent.com/1427284/37708894-b602fec6-2cde-11e8-9402-81799bd698bc.png)

What version of .NET and what OS are you on?

**Comment by asiridissa** [comment]
Im on Windows 10 Pro 1709 and .Net 4.7.02556.
Here is my last scenario.
1. Delete a file.
2. Change the version.
3. Ctrl+S (Saves fine).
Then Ctrl+S again will prompt the error.
If I select the publish menu, also error prompts.

![2](https://user-images.githubusercontent.com/3539388/37750475-4258b1d4-2db3-11e8-9f16-0437195b8736.PNG)

**Comment by onovotny** [comment]
Thanks. I can repro now on save. Investigating.

**Comment by mmoore99** [comment]
Any update on this issue? I am experiencing the same problem.

**Comment by simonlaszcz** [comment]
Is there a workaround for this?

**Comment by igitur** [comment]
I ran NPE from source and got this problem too. The exception occurs in `System.IO.Packaging`, so I think it's a bug there. Sorry, I don't have the stack trace anymore. Will try to reproduce later.

So what I did was repackage the `.nupkg` file manually (renamed to zip, extract, rezip, rename to .nupkg). That fixed my issue.

**Comment by igitur** [comment]
Stack trace:
```
   at System.IO.Compression.ZipArchiveEntry.OpenInReadMode(Boolean checkOpenable)
   at NuGet.Packaging.PackageArchiveReader.GetStream(String path)
   at NuGetPe.ZipPackageFile.<>c__DisplayClass1_0.<.ctor>b__0() in C:\dev\NuGetPackageExplorer\Core\Packages\ZipPackageFile.cs:line 18
   at NuGetPe.ZipPackageFile.GetStream() in C:\dev\NuGetPackageExplorer\Core\Packages\ZipPackageFile.cs:line 35
   at PackageExplorerViewModel.PackageFile.GetStream() in C:\dev\NuGetPackageExplorer\PackageViewModel\PackagePart\PackageFile.cs:line 56
   at NuGet.Packaging.PackageBuilder.WriteFiles(ZipArchive package, HashSet`1 filesWithoutExtensions)
   at NuGet.Packaging.PackageBuilder.Save(Stream stream)
   at PackageExplorerViewModel.PackageHelper.SavePackage(IPackageMetadata packageMetadata, IEnumerable`1 files, String targetFilePath, Boolean useTempFile) in C:\dev\NuGetPackageExplorer\PackageViewModel\Utilities\PackageHelper.cs:line 34
   at PackageExplorerViewModel.SavePackageCommand.SavePackage(String fileName) in C:\dev\NuGetPackageExplorer\PackageViewModel\Commands\SavePackageCommand.cs:line 265
```

**Comment by igitur** [comment]
I experienced this bug again when I saved a package. I then published it to NuGet the without an exception. But then it turns out the published package https://www.nuget.org/packages/ClosedXML/0.93.0-beta3 was corrupt.

**Comment by Toemsel** [comment]
Same issue here
