### ISSUE TITLE
System.ComponentModel.Win32Exception in :0

### ISSUE THREAD

**Issue by onovotny** [NuGetPackageExplorer/NuGetPackageExplorer#509]
## Error in NuGet Package Explorer

**System.ComponentModel.Win32Exception** in **:0**
The operation was canceled by the user

[View on Bugsnag](https://app.bugsnag.com/oren-novotny-llc/nuget-package-explorer/errors/5bdfb54af79f4d001a6d8dc7?event_id=5bdfbeb0003088469daf0000&i=gh&m=ci)

## Stacktrace

    :0 - PackageExplorer.UriHelper.OpenExternalLink(Uri licenseUrl)
    :0 - PackageExplorer.PluginManagerDialog.GoToPageCommand_Executed(object sender, ExecutedRoutedEventArgs e)
    :0 - PackageExplorer.MainWindow.AddPluginFromAssembly_Click(object sender, RoutedEventArgs e)
    :0 - PackageExplorer.App.Main()

[View full stacktrace](https://app.bugsnag.com/oren-novotny-llc/nuget-package-explorer/errors/5bdfb54af79f4d001a6d8dc7?event_id=5bdfbeb0003088469daf0000&i=gh&m=ci)

*Created by Oren Novotny via Bugsnag*

**Comment by campersau** [comment]
Is this the same stacktrace as above or is it some other use of `Process.Start` like the following which aren't catched?
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/f27b49c46a57d982472c7967e64d216d2e7d07b1/PackageExplorer/MainWindow.xaml.cs#L613
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/f27b49c46a57d982472c7967e64d216d2e7d07b1/PackageViewModel/Utilities/FileHelper.cs#L62
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/f27b49c46a57d982472c7967e64d216d2e7d07b1/PackageViewModel/Utilities/FileHelper.cs#L95
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/4aa673e661b3256050e333973e5e7e22bb5ba627/PackageExplorer/PackageChooser/PackageDetailControl.xaml.cs#L19

**Comment by onovotny** [comment]
Full stack trace:

```
System.ComponentModel.Win32Exception: The operation was canceled by the user
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at PackageExplorer.UriHelper.OpenExternalLink(Uri licenseUrl)
   at PackageExplorer.PluginManagerDialog.GoToPageCommand_Executed(object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandBinding.OnExecuted(object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandManager.ExecuteCommandBinding(object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)
   at System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, object sender, RoutedEventArgs e, ICommand command, bool execute)
   at System.Windows.Input.CommandManager.FindCommandBinding(object sender, RoutedEventArgs e, ICommand command, bool execute)
   at System.Windows.Input.CommandManager.OnExecuted(object sender, ExecutedRoutedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(object source, RoutedEventArgs args, bool reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(object parameter, IInputElement target, bool userInitiated)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, bool userInitiated)
   at System.Windows.Documents.Hyperlink.OnClick()
   at System.Windows.Documents.Hyperlink.DoUserInitiatedNavigation(object sender)
   at System.Windows.Documents.Hyperlink.OnMouseLeftButtonUp(object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(object source, RoutedEventArgs args, bool reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(object source, RoutedEventArgs args, bool reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, int timestamp, RawMouseActions actions, int x, int y, int wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, object args, int numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(ref MSG msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(object booleanBox)
   at System.Windows.Window.ShowDialog()
   at PackageExplorer.MainWindow.AddPluginFromAssembly_Click(object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(object source, RoutedEventArgs args, bool reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, object args, int numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(ref MSG msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at PackageExplorer.App.Main()
```

**Comment by onovotny** [comment]
Thanks @campersau, good catch. Forgot to check other usages of `Process.Start`
