### ISSUE TITLE
FIPS compliance bug in WinAPI Code Pack: System.TypeInitializationException 

### ISSUE THREAD

**Issue by onovotny** [NuGetPackageExplorer/NuGetPackageExplorer#514]
## Error in NuGet Package Explorer

**System.TypeInitializationException** in **:0**
The type initializer for 'Microsoft.WindowsAPICodePack.Shell.ShellObject' threw an exception.

[View on Bugsnag](https://app.bugsnag.com/oren-novotny-llc/nuget-package-explorer/errors/5bdfa3f2028965001933b8f7?event_id=5be1ff6700309b658a410000&i=gh&m=ci)

## Stacktrace

    D:\a\1\s\PackageExplorer\MefServices\UIServices.cs:237 - PackageExplorer.UIServices.OpenFolderDialog(string title, string initialPath, out string selectedPath)
    D:\a\1\s\PackageViewModel\PackageViewModel.cs:801 - PackageExplorerViewModel.PackageViewModel.ExportExecute()
    D:\a\1\s\PackageViewModel\Commands\RelayCommand.cs:145 - PackageExplorerViewModel.RelayCommand.Execute(object parameter)
    :0 - PackageExplorer.App.Main()

[View full stacktrace](https://app.bugsnag.com/oren-novotny-llc/nuget-package-explorer/errors/5bdfa3f2028965001933b8f7?event_id=5be1ff6700309b658a410000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by onovotny** [comment]
Full stack trace

```
System.TypeInitializationException: The type initializer for 'Microsoft.WindowsAPICodePack.Shell.ShellObject' threw an exception. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   at Microsoft.WindowsAPICodePack.Shell.ShellObject..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAPICodePack.Shell.ShellObject.op_Inequality(ShellObject leftShellObject, ShellObject rightShellObject)
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ApplyNativeSettings(IFileDialog dialog)
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ShowDialog()
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ShowDialog(Window window)
   at PackageExplorer.UIServices.OpenFolderDialog(string title, string initialPath, out string selectedPath) in D:\a\1\s\PackageExplorer\MefServices\UIServices.cs:line 237
   at PackageExplorerViewModel.PackageViewModel.ExportExecute() in D:\a\1\s\PackageViewModel\PackageViewModel.cs:line 801
   at PackageExplorerViewModel.RelayCommand.Execute(object parameter) in D:\a\1\s\PackageViewModel\Commands\RelayCommand.cs:line 145
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, bool userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, object args, int numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(ref MSG msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at PackageExplorer.App.Main()
```

**Comment by vcsjones** [comment]
Eh. That's pretty gnarly. You _can_ disable the FIPS check across the board using:

```xml
<configuration>
    <runtime>
        <enforceFIPSPolicy enabled="false"/>
    </runtime>
</configuration>
```

I'm not sure if that would be disingenuous or not. It looks like the MD5 call is only used in `GetHashCode` which is obviously not a security sensitive API. However that flag is global and perhaps it is using MD5 elsewhere that would make it sensitive.

It's hashing the ITEMIDLIST that it looks like it's using just the first 4 bytes of the MD5 hash and converting it to a little-endian signed int.

It's 1. weird to use MD5 in `GetHashCode`. Seems like the Code Pack confused "Cryptographic Hash" and "Hash bucket hash". and 2. weird to use MD5 at all.

**Comment by onovotny** [comment]
Given that NPE is capable of performing cryptographic operations  (signing/validating) packages, I'm not too keen on disabling the FIPS policy if someone has it turned on...

**Comment by onovotny** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**System.InvalidOperationException** in **:0**](https://app.bugsnag.com/oren-novotny-llc/nuget-package-explorer/errors/5bdfa3f2028965001933b8f7?event_id=5be7e9b200308002545f0000&i=gh&m=fx)

**Comment by onovotny** [comment]
An error linked to this issue has been reopened in Bugsnag
[**System.InvalidOperationException** in **:0**](https://app.bugsnag.com/oren-novotny-llc/nuget-package-explorer/errors/5bdfa3f2028965001933b8f7?event_id=5beeb0fc0030998d544c0000&i=gh&m=ra)

**Comment by onovotny** [comment]
An error linked to this issue has been reopened in Bugsnag
[**System.InvalidOperationException** in **:0**](https://app.bugsnag.com/oren-novotny-llc/nuget-package-explorer/errors/5bdfa3f2028965001933b8f7?event_id=5c0378570031edae087e0000&i=gh&m=ra)

**Comment by onovotny** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**System.InvalidOperationException** in **:0**](https://app.bugsnag.com/oren-novotny-llc/nuget-package-explorer/errors/5bdfa3f2028965001933b8f7?event_id=5c0378570031edae087e0000&i=gh&m=fx)

**Comment by onovotny** [comment]
Closed as not applicable to the .NET Core version
