### ISSUE TITLE
Cannot install Application (codeplex 500)

### ISSUE THREAD

**Issue by brentarias** [NuGetPackageExplorer/NuGetPackageExplorer#63]
I tried to install 3.11 using NugetPackageExplorer.application.  It failed and provided these details:

PLATFORM VERSION INFO
	Windows 			: 10.0.10240.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1055.0 built by: NETFXREL2
	clr.dll 			: 4.6.1055.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1055.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.10240.16384 (th1.150709-1700)

SOURCES
	Deployment url			: file:///C:/Users/baria/Downloads/NuGetPackageExplorer.application
	Deployment Provider url		: https://npe.codeplex.com/releases/clickonce/NuGetPackageExplorer.application
						Server		: Microsoft-IIS/7.5,CDS02
						X-Powered-By	: ASP.NET
						X-AspNet-Version: 4.0.30319

IDENTITIES
	Deployment Identity		: NuGetPackageExplorer.application, Version=3.11.0.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86

APPLICATION SUMMARY
	* Installable application.
	* Trust url parameter is set.
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\baria\Downloads\NuGetPackageExplorer.application resulted in exception. Following failure messages were detected:
		+ Downloading https://npe.codeplex.com/releases/clickonce/Application Files/NuGetPackageExplorer_3_11_0_0/NuGetPackageExplorer.exe.manifest did not succeed.
		+ The remote server returned an error: (500) Internal Server Error.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [2/25/2016 3:20:35 PM] : Activation of C:\Users\baria\Downloads\NuGetPackageExplorer.application has started.
	* [2/25/2016 3:20:36 PM] : Processing of deployment manifest has successfully completed.
	* [2/25/2016 3:20:36 PM] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [2/25/2016 3:21:06 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading https://npe.codeplex.com/releases/clickonce/Application Files/NuGetPackageExplorer_3_11_0_0/NuGetPackageExplorer.exe.manifest did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The remote server returned an error: (500) Internal Server Error.
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by 304NotModified** [comment]
```
The remote server returned an error: (500) Internal Server Error.
```

That's an error from CodePlex. I think we cannot fix this, can you try another time?

**Comment by 304NotModified** [comment]
I tried re-installing it, and it worked

**Comment by 304NotModified** [comment]
@Mystagogue do you have still these problems?
