### ISSUE TITLE
Bug : v5.2.47 : Cannot open packages anymore. App crashes

### ISSUE THREAD

**Issue by MscrmTools** [NuGetPackageExplorer/NuGetPackageExplorer#716]
It worked with previous version

Windows 10 1803

Installed from Windows Store. Updated today, packages don't open and app crashes and closes itself

**Comment by campersau** [comment]
It is also crashing on my machine. Here is the event log (in german):

```
Application: NuGetPackageExplorer.exe
CoreCLR Version: 4.700.19.30373
.NET Core Version: 
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Unbekannte ModifierKeys "STRG".

Resulting in: Beim Festlegen der Eigenschaft "System.Windows.Controls.Primitives.ButtonBase.Command" wurde eine Ausnahme ausgelöst.

Resulting in: An exception occurred while trying to create an instance of type 'PackageExplorer.MainWindow'.

Resulting in: Cannot activate part 'PackageExplorer.MainWindow'.
Element: PackageExplorer.MainWindow -->  PackageExplorer.MainWindow -->  AssemblyCatalog (Assembly="NuGetPackageExplorer, Version=5.2.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot get export 'PackageExplorer.MainWindow (ContractName="PackageExplorer.MainWindow")' from part 'PackageExplorer.MainWindow'.
Element: PackageExplorer.MainWindow (ContractName="PackageExplorer.MainWindow") -->  PackageExplorer.MainWindow -->  AssemblyCatalog (Assembly="NuGetPackageExplorer, Version=5.2.0.0, Culture=neutral, PublicKeyToken=null")

   at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.CatalogExport.GetExportedValueCore()
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValueCore[T](String contractName, ImportCardinality cardinality)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValue[T](String contractName)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValue[T]()
   at PackageExplorer.App.Application_Startup(Object sender, StartupEventArgs e) in d:\a\1\s\PackageExplorer\App.xaml.cs:line 69
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at PackageExplorer.App.Main()
```

#717 might be a duplicate

**Comment by campersau** [comment]
@MscrmTools do you get the same error in the event viewer?

@onovotny compiling and running the master (and tagged commit) as store and nightly versions does work on my machine without any problems.

**Comment by onovotny** [comment]
@campersau I'm seeing a lot of these errors in telemetry as well. The interesting part is that none of them are from English cultures. 

Any chance you can dig a little since it's happening for you?

**Comment by onovotny** [comment]
Possibly related https://github.com/dotnet/wpf/issues/684

**Comment by campersau** [comment]
@onovotny the tests I have made in my last comment were made using the package project as startup project and they worked fine.
I am using dotnet 3.0.100-preview5-011568

**Comment by onovotny** [comment]
@campersau I suspect a regression in preview 6, are you able to try that? https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/3.0.1xx/dotnet-sdk-latest-win-x64.exe

**Comment by campersau** [comment]
I installed dotnet `3.0.100-preview6-012264` and can see the error during debugging.

![image](https://user-images.githubusercontent.com/4009570/59269242-e80cc700-8c4e-11e9-8bf7-03a163a21ba9.png)

```
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Nachricht = Zeilennummer "69" und Zeilenposition "18" von "Beim Festlegen der Eigenschaft "System.Windows.Controls.Primitives.ButtonBase.Command" wurde eine Ausnahme ausgelöst.".
  Quelle = PresentationFramework
  Stapelüberwachung:
   bei System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   bei System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   bei System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   bei System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   bei PackageExplorer.MainWindow.InitializeComponent() in C:\dev_projects\NuGetPackageExplorer\PackageExplorer\MainWindow.xaml: Zeile1

Innere Ausnahme 1:
NotSupportedException: Unbekannte ModifierKeys "STRG".
```

**Comment by onovotny** [comment]
Thanks for confirming. I'll try to escalate. In the interim, I've reverted to preview 5 in the build and that's deploying through the store.

**Comment by MscrmTools** [comment]
The error I got is in French OS.
It happens also when creating a brand new package

**Comment by campersau** [comment]
The issue is fixed for me with the new NuGet Package Explorer 5.2.49 version. @MscrmTools can you please try the update too?

![image](https://user-images.githubusercontent.com/4009570/59270409-afbab800-8c51-11e9-8c21-80f0763bc6e4.png)

@onovotny let me know when I can do a test with another dotnet version :)

**Comment by MscrmTools** [comment]
Yes, fixed too with this version

**Comment by onovotny** [comment]
Great to hear. I'll keep this issue to track the underlying external WPF issue and will close once there's a fix in WPF.

**Comment by onovotny** [comment]
@campersau Can you install the latest Preview 7 and see if it has the fix in it? 

https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe

**Comment by campersau** [comment]
@onovotny This bug is fixed but I got some compilation errors:

- `System.Windows.Forms` can not be referenced.
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/6e9fcf092fdbb7189159e57731cd4bb10a5c7011/PackageExplorer/MefServices/UIServices.cs#L259

- `System.Drawing.Icon` is missing.
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/6e9fcf092fdbb7189159e57731cd4bb10a5c7011/PackageViewModel/Utilities/FileHelper.cs#L326
