### ISSUE TITLE
Can no longer browse Nuget Feed to add dependancies

### ISSUE THREAD

**Issue by CodeSeraph** [NuGetPackageExplorer/NuGetPackageExplorer#850]
**Type**:

- Bug : **Can no longer browse NuGet Feeds to add dependancies**

**OS version**: (Windows 10 Pro)

**Installed from**: Microsoft Store 

In case of a BUG:

- What is the current result? Browse online NuGet feed
- What is the expected result? View all NuGet Packages

**Comment by onovotny** [comment]
Can you please provide repro steps?

I just tried this and it works for me.

![image](https://user-images.githubusercontent.com/1427284/68531770-03562e00-02e4-11ea-8bd0-11813a1d02cd.png)

I click there, it shows me the package chooser, I double-click a package, then it enters it. Then hitting the + adds it.

![image](https://user-images.githubusercontent.com/1427284/68531794-284aa100-02e4-11ea-95b3-a6b212623c18.png)

**Comment by CodeSeraph** [comment]
Hi

 

Thanks for responding. I had this issue for about 2 days and no matter the nuget source it didn’t seem to work. I have however tried again and it seems to be working. Not sure what might have gone wrong.

 

But thanks for following up and great work on the app, I use it often.

**Comment by ivanm07** [comment]
I get the same error: 
Application: NuGetPackageExplorer.exe
CoreCLR Version: 5.0.20.51904
.NET Version: 5.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: NuGet.Configuration.NuGetConfigurationException: NuGet.Config is not valid XML. Path: 'C:\Users\ivan.mireles\AppData\Roaming\NuGet\NuGet.Config'.
 ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.Configuration.XmlUtility.LoadSafe(Stream input, LoadOptions options)
   at NuGet.Configuration.XmlUtility.GetDocument(String fullPath)
   at NuGet.Configuration.XmlUtility.GetOrCreateDocument(XDocument content, String fullPath)
   at NuGet.Configuration.SettingsFile.<>c__DisplayClass23_0.<.ctor>b__0()
   at NuGet.Configuration.SettingsFile.<>c__DisplayClass32_0.<ExecuteSynchronized>b__0()
   --- End of inner exception stack trace ---
   at NuGet.Configuration.SettingsFile.<>c__DisplayClass32_0.<ExecuteSynchronized>b__0()
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLocked(String filePath, Action action)
   at NuGet.Configuration.SettingsFile.ExecuteSynchronized(Action ioOperation)
   at NuGet.Configuration.SettingsFile..ctor(String directoryPath, String fileName, Boolean isMachineWide, Boolean isReadOnly)
   at NuGet.Configuration.Settings.ReadSettings(String settingsRoot, String settingsPath, Boolean isMachineWideSettings, Boolean isAdditionalUserWideConfig, SettingsLoadingContext settingsLoadingContext)
   at NuGet.Configuration.Settings.LoadUserSpecificSettings(String root, String configFileName, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at NuGet.Configuration.Settings.LoadSettingsForSpecificConfigs(String root, String configFileName, List`1 validSettingFiles, IMachineWideSettings machineWideSettings, Boolean loadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
   at NuGet.Configuration.Settings.LoadSettings(String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean loadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
   at NuGet.Configuration.Settings.LoadDefaultSettings(String root)
   at PackageExplorer.SettingsManager.GetPackageSources() in D:\a\1\s\PackageExplorer\MefServices\SettingsManager.cs:line 159
   at PackageExplorerViewModel.PackageSourceSettings.GetSources() in /_/PackageViewModel/PackageChooser/PackageSourceSettings.cs:line 28
   at PackageExplorerViewModel.MruPackageSourceManager.LoadDataFromSettings() in /_/PackageViewModel/MruPackageSourceManager.cs:line 32
   at PackageExplorerViewModel.MruPackageSourceManager..ctor(ISourceSettings sourceSettings) in /_/PackageViewModel/MruPackageSourceManager.cs:line 17
   at PackageExplorerViewModel.PackageViewModelFactory.CreatePackageChooserViewModel(String fixedPackageSource) in /_/PackageViewModel/PackageViewModelFactory.cs:line 87
   at PackageExplorer.PackageChooserService.SelectPackage(String searchTerm) in D:\a\1\s\PackageExplorer\MefServices\PackageChooserService.cs:line 44
   at PackageExplorer.MainWindow.OpenPackageFromRepository(String searchTerm) in D:\a\1\s\PackageExplorer\MainWindow.xaml.cs:line 357
   at PackageExplorer.MainWindow.OpenFeedItem_Click(Object sender, ExecutedRoutedEventArgs e) in D:\a\1\s\PackageExplorer\MainWindow.xaml.cs:line 331
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at PackageExplorer.App.Main()

**Comment by campersau** [comment]
@ivanm07 Your `C:\Users\ivan.mireles\AppData\Roaming\NuGet\NuGet.Config` seems to be corrupt. Can you please rename or delete it? Then it should work again. You can also edit it in a code editor to see what exactly is not XML conform.

**Comment by ivanm07** [comment]
> @ivanm07 Your `C:\Users\ivan.mireles\AppData\Roaming\NuGet\NuGet.Config` seems to be corrupt. Can you please rename or delete it? Then it should work again. You can also edit it in a code editor to see what exactly is not XML conform.

Yes that works for me, thanks!

**Comment by clairernovotny** [comment]
Closing due to age. We've seen corruption in that file before but it's not clear why.
